### ISSUE TITLE
As a user I want to login using my email so that I can have full access to the application.

### ISSUE THREAD

**Issue by sethryan007** [xlab-classes/cse442-spring2022-team-unemployed-bums#23]
**Acceptance Tests**

*Test 1*
1. Go to https://www-student.cse.buffalo.edu/unemployed-bums/
2. Verify that there is a login form with email and password fields
3. Enter for email: myAccountTest1@gmail.com and password: Account1
4. Click the login button
5. Verify that you have been brought to the homepage

**Comment by couchkevin** [comment]
Instead of emails, we decided to instead use usernames
