### ISSUE TITLE
Replace local database with mysql database provided on the server

### ISSUE THREAD

**Issue by jay3393** [xlab-classes/cse442-spring2022-team-unemployed-bums#65]
Acceptance Tests

Test:

1. Register a new user using www-cse.buffalo.edu:8001/login
2. Go to https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/
3. Login and verify under auth_user that a new user was added
4.  Verify that the passwords are hashed and salted

**Comment by couchkevin** [comment]
Connected the database with the CSE server SQL database

**Comment by couchkevin** [comment]
#71
