### ISSUE TITLE
As a user I want to be able to register a new account using my email so that I can use the application.

### ISSUE THREAD

**Issue by sethryan007** [xlab-classes/cse442-spring2022-team-unemployed-bums#8]
**Acceptance Tests:**

Test 1:
1. In a web browser go to OurWebsiteFor442.com
2. Select the create account option
3. Enter the email address myAccountTest1@gmail.com, and the password ThisIsATest1
4. Select done to create the account and by directed to the home page.
5. Close the browser and open it again.
6. Navigate to OurWebsiteFor442.com
7. In the login section enter myAccountTest1@gmail.com and in the password section enter ThisIsATest1 and select login to be directed to the homepage.

**Comment by couchkevin** [comment]
Using Usernames for now but will be able to sign in using username/email when forgot password functionality is added/ more functionality that includes emails is added.
